### ISSUE TITLE
Should protein sequence, and not accession number, be first-class?

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/genotype-network#39]
I noticed in the genotype network construction procedure, the accession number is the node. Should it be changed to amino acid sequence, with the accession numbers listed as a piece of metadata associated with the node?

**Comment by pharos916** [comment]
Correct. According to the in-line documentation, the graph nodes should be the individual HA sequences. The dictionary self.sequences should have keys = accession number and value = SeqRecord. 

Is the bug from the line "for seq in self.sequences.keys():"? I'm assuming that accessing self.sequences.keys() gets the accession numbers rather than the sequence?

**Comment by ericmjl** [comment]
That's right. I have merged a PR that deals with this issue. Problem is, even after PR merge, the newly updated package (on my own environment on Rous) still uses accessions and not amino acid letters (represented as `str`) as the nodes. There's some bug here, also working on the bug fix right now.

**Comment by ericmjl** [comment]
Turns out the bug was not in the package, but in my own script. Closing this issue.
